spring:
  batch:
    job:
      names: ${job.name:NOME}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:h2:./data/springBatch
    driver-class-name: org.h2.Driver
    username: sa
    password: 1111
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      path: /h2console
      enabled: true

